### ISSUE TITLE
v0.1.0 published to pypi missing requirements.txt

### ISSUE THREAD

**Issue by zdw** [rasjani/robotframework-importresource#1]
Thanks for writing this library, it's quite useful!

I found a bug - when trying to install version 0.1.0 that is published to pypi: https://pypi.org/project/robotframework-importresource/

I get this error:
```
$ pip install robotframework-importresource
Collecting robotframework-importresource
  Using cached https://files.pythonhosted.org/packages/5a/4d/ef3938934d5aae5da918762ac8ea19a8e53fc6f082398fb5704bd8efc13a/robotframework-importresource-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gt/f7qz30x558j7gggqvv_8dc_w0000gq/T/pip-install-9f4w3jl2/robotframework-importresource/setup.py", line 9, in <module>
        with open(join(CWD, "requirements.txt"), encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/gt/f7qz30x558j7gggqvv_8dc_w0000gq/T/pip-install-9f4w3jl2/robotframework-importresource/requirements.txt'
```

Installing from the repo with a git+https:// URL works correctly, so I think this is a packaging problem. Could you publish a newer version to PyPI?

**Comment by rasjani** [comment]
fix pushed
